### ISSUE TITLE
This project will only accept links from Solace Email not direct links

### ISSUE THREAD

**Issue by KenBarr** [SolaceLabs/solace-aws-ha-quickstart#1]
If a customer is unable to receive a Solace email with the re-direct link they cannot use this project.

**Comment by KenBarr** [comment]
At this point we are going to deal with this type of problem on an individual bases.  If it becomes a large issue then we need to fix our registration process, not work around it at the individual project.

**Comment by solacedbaik** [comment]
Following up on this to clarify  - if this template were to be used for production purposes (or perhaps a customized version of it), it would need to be able to get the VMR from a variety of sources or be more flexible in the source of the VMR image - e.g. an AMI, s3 bucket, arbitrary HTTP/S URL.  If it can only be used for evaluation / temporary testing purposes it would greatly limit the usefulness of it.  How difficult would it be to tweak the template to allow this (assuming it's only a template change)?
