### ISSUE TITLE
Port 80 should be opened for "Allowed External Access CIDR"s

### ISSUE THREAD

**Issue by gbertin** [SolaceLabs/solace-aws-ha-quickstart#10]
I wanted to test JS clients and found port 80 for SMF/WEB clients was properly enabled on the VMR but an inbound rule opening the port was not added to an AWS security group. Given the user specifies "Allowed External Access CIDRs" I see no reason port 80 should not be opened for such source IPs as well.

**Comment by KenBarr** [comment]
Fixed:

https://github.com/SolaceLabs/solace-aws-ha-quickstart/commit/fa9c532e0fa8c87f45ec1f2a7c8b3947dbed49af
