### ISSUE TITLE
ec2-user on docker host not part of docker group

### ISSUE THREAD

**Issue by solacedbaik** [SolaceLabs/solace-aws-ha-quickstart#11]
The ec2-user isn't part of the docker user so sudo is needed for all docker commands.  In contrast, the Azure QS template adds the user to the docker group.

**Comment by KenBarr** [comment]
fixed in install-solace might want to move to the cf template if possible.

**Comment by KenBarr** [comment]
commit info: 
https://github.com/SolaceLabs/solace-aws-ha-quickstart/commit/fa9c532e0fa8c87f45ec1f2a7c8b3947dbed49af
