### ISSUE TITLE
config-sync status shows as down after startup

### ISSUE THREAD

**Issue by solacedbaik** [SolaceLabs/solace-aws-ha-quickstart#12]
After starting up the VMRs, config-sync shows as "Down":

Oper Status:  Down (local table has a problem: (0,Router,'site') [Out-Of-Sync])

The backup router shows repeating log entries similar to the following:

2017-09-21T12:27:31+0000 <local3.info> ip-10-0-144-122 event: SYSTEM: SYSTEM_CLIENT_CONNECT_FAIL: - - Message VPN (#config-sync) Sol Client username #config-sync clientname
 #config-sync/backup connect failed from 10.0.144.122:37377 - Service Unavailable: Service Unavailable

I can see that the SMF service and VPN is up so not sure what's causing this.

**Comment by KenBarr** [comment]
Is this transient?
What is the state of redundancy?
If you assert-master from one side does it come up?

**Comment by solacedbaik** [comment]
It appears to only occur after the VMRs are first started by the template (I tested this a few times).  When I restarted them manually, config-sync came backup.  I haven't tried doing an assert-master, although I tried to resync-master on the backup and that didn't work.  Can you repro it?  I can test the assert-master next.

**Comment by solacedbaik** [comment]
Redundancy was up on both nodes - just config-sync was down.

**Comment by KenBarr** [comment]
assert-master resolved this issue, will look to automate:

ip-172-31-7-209# show config-sync

Admin Status                      : Enabled
Oper Status                       : Down (local table has a problem:
                                      (0,Router,'site') [Out-Of-Sync])
<snip>

ip-172-31-7-209# admin
ip-172-31-7-209(admin)# config-sync
ip-172-31-7-209(admin/config-sync)# assert-master router
Processed 1 config-sync tables.
ip-172-31-7-209(admin/config-sync)# show config-sync

Admin Status                      : Enabled
Oper Status                       : Down (remote redundancy table has a
                                      problem: (0,Router,'site') [In-Sync])
<snip>

ip-172-31-7-209(admin/config-sync)# assert-master message-vpn default
WARNING: This command can temporarily disconnect clients on the
AD-inactive appliance. Clients connected to this appliance will not
be affected.
Do you want to continue (y/n)? y

Processed 1 config-sync tables.
ip-172-31-7-209(admin/config-sync)# show config-sync

Admin Status                      : Enabled
Oper Status                       : Up
<snip>

**Comment by solacedbaik** [comment]
Confirmed - assert-master also worked for me.

On a side note - if I did a resync-master on the backup afterwards, it caused config-sync to get out of sync again, but eventually it was able to resync (took about 10-15 sec).  Automation for just assert-master on one side should do the trick.

**Comment by KenBarr** [comment]
fix committed and deployed to s3. 
https://github.com/SolaceLabs/solace-aws-ha-quickstart/commit/a9cba3dc72319c8e3151eca4a868c35e5516ffb4
