### ISSUE TITLE
Instances can't be temporarily stopped

### ISSUE THREAD

**Issue by solacedbaik** [SolaceLabs/solace-aws-ha-quickstart#2]
There doesn't appear to be a way to deliberately stop instances without destroying the stacks.  This might be useful for maintenance or development purposes.

**Comment by KenBarr** [comment]
This is an artifact of auto-scaling.    You can disable autoscaling so you can stop/start instances. and then later turn autoscaling back on.

From and of the node in the ha tuple issue this command, correct for region, eg. us-east-1:
aws autoscaling describe-auto-scaling-groups --region us-east-1 | grep ResourceId

Result will be multiple lines for the Primary, Backup, Monitor
                    "ResourceId": "Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0",
                    "ResourceId": "Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterPrimaryStack-AMAE6N1J72BZ-Nodes-D95RTQ3107P2",
                    "ResourceId": "Solace-HA-SolaceStack-1KQ1ZJD19C08C-MonitorStack-XA6ZYEQXALPF-Nodes-1DWGAHIGRGLPJ",

Now suspend autoscaling:
aws autoscaling suspend-processes --region us-east-1 --auto-scaling-group-name Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0
aws autoscaling suspend-processes --region us-east-1 --auto-scaling-group-name Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0
aws autoscaling suspend-processes --region us-east-1 --auto-scaling-group-name Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0

You can now stop and start instances as you wish.  To turn autoscaling back on:
aws autoscaling resume-processes --region us-east-1 --auto-scaling-group-name Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0
aws autoscaling resume-processes --region us-east-1 --auto-scaling-group-name Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0
aws autoscaling resume-processes --region us-east-1 --auto-scaling-group-name Solace-HA-SolaceStack-1KQ1ZJD19C08C-MessageRouterBackupStack-1SL8XN62T8SFJ-Nodes-1KLFZINYC6BY0



Let me know if this is good enough.

**Comment by solacedbaik** [comment]
Oddly, I get different output (no ResourceId) for my region.  However, I was able to manually stop / start processes after setting the autoscaling group instances to standby.  So either of these methods could be sufficient.

**Comment by solacedbaik** [comment]
Also, shouldn't the command be run for primary and monitor stacks, instead of 3 times for the backup stack in your example?

**Comment by KenBarr** [comment]
You should be able to suspend from anywhere in the cluster.

**Comment by KenBarr** [comment]
This is an AWS autostart issue not specific to this project.  How to suspend autostart described in this ticket.
