### ISSUE TITLE
Primary is not the active node by default

### ISSUE THREAD

**Issue by solacedbaik** [SolaceLabs/solace-aws-ha-quickstart#3]
After starting up a cluster using the template, the primary node isn't active.  I had to reset the message spool on both nodes to get both the spool and redundancy back into the expected state.  Not sure if this is a transient issue but I've seen it several times when starting a cluster from scratch.

**Comment by KenBarr** [comment]
Do you think this is a template issue or an actual Solace product issue?

**Comment by solacedbaik** [comment]
I'm guessing it's a template issue, perhaps related to startup timing issues.  Are you able to repro this?

**Comment by KenBarr** [comment]
I have this issue raised: [Solace Support #24294] HA pair stuck in Local Inactive, which you might also be hitting, not sure.

**Comment by KenBarr** [comment]
Workaround implemented and product enhancement raised.  Closing ticket,
