### ISSUE TITLE
Resource Creation Failed for 2nd HA Pair deployment

### ISSUE THREAD

**Issue by sumeetkoshal** [SolaceLabs/solace-aws-ha-quickstart#5]
I am getting the below error when trying to create another HA pair in different VPC/subnet…

Embedded stack arn:aws:cloudformation:us-east-1:583592505368:stack/XXXXXXX-2-Solace-HA-SolaceStack-1B0BQW8WTZOOJ-MessageRouterPrimaryInterfaceStack-1U4683D5KFRNU/5a243eb0-51fd-11e7-a2a7-50d5ca6e60ae was not successfully created: The following resource(s) failed to create: [networkInterface].

The following resource(s) failed to create: [InstanceProfile, MessageRouterPrimaryInterfaceStack, MessageRouterBackupInterfaceStack].

**Comment by KenBarr** [comment]
Please provide parameters provided to top level stack parameters.  You can get this from the [Parameters] tab in the stack details

**Comment by sumeetkoshal** [comment]
AdminPassword	admin
AvailabilityZones	us-east-1a,us-east-1b,us-east-1c
BootDiskSize	24
KeyPairName	elliemae_keypair
LinuxOSAMI	Amazon-Linux-HVM
MessageRouterNodeInstanceType	t2.large
MessageRouterNodeSpotPrice	0.00
MessageRouterNodeStorage	0
MonitorNodeInstanceType	t2.large
MonitorNodeSpotPrice	0.00
MonitorNodeStorage	0
NumberOfAZs	3
PrivateSubnet1CIDR	10.0.136.128/25
PrivateSubnet2CIDR	10.0.137.128/25
PublicSubnet1CIDR	10.0.136.0/25
PublicSubnet2CIDR	10.0.137.0/25
PublicSubnet3CIDR	10.0.138.0/25
QSS3BucketName	solace-aws-ha-quickstart
QSS3KeyPrefix	forMikeH
RemoteAccessCIDR	0.0.0.0/0
SolaceDockerURL	http://em.solace.com/MY0I0u0sCo51i00xd0cB0x0
SSHAccessCIDR	0.0.0.0/0
VPCCIDR	10.0.136.0/22

**Comment by KenBarr** [comment]
It looks like to are showing me the higher stack error and not the error from the interface stack, so no way of knowing what the actual error is.  If you still have the interface stack, does it have an error?

**Comment by sumeetkoshal** [comment]
I have deleted everything and reran the script as I might have to demo today.

I will try to simulate this and let you know if that happens.

Sent from my iPhone

On Jun 16, 2017, at 5:12 AM, Ken Barr <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like to are showing me the higher stack error and not the error from the interface stack, so no way of knowing what the actual error is. If you still have the interface stack, does it have an error?

**Comment by KenBarr** [comment]
In-ability to create a Elastic Network interface might have been a EIP allocation issue.  Anyway we are not using this approach any more so I am closing this issue.  Might have o re-test and rebustify requests for AWS objects down the road.
