### ISSUE TITLE
Quickstart documentation issue

### ISSUE THREAD

**Issue by gbertin** [SolaceLabs/solace-aws-ha-quickstart#9]
From https://s3.amazonaws.com/quickstart-reference/solace/vmr/latest/doc/solace-vmr-on-the-aws-cloud.pdf:

This text appears wrong:

"The Quick Start will create three EC2 instances for the message router primary and backup instances, and the monitor instance, and assign them meaningful names.You'll see these listed in the Outputs tab of the AWS CloudFormation console, as illustrated in Figure 2"

I don't see them. I can see this in the Outputs tab if I select a sub-template:

![image](https://user-images.githubusercontent.com/19395920/30496383-35a51150-9a1d-11e7-8f02-87b60e54dafc.png)

But that is not what is documented. What is documented looks like an EC2 instance screen. Not a CloudFormation Output tab screen

**Comment by KenBarr** [comment]
Though likely a valid bug, it is raised against the wrong project in the wrong repo.  I believe you want to raise it here: https://github.com/aws-quickstart/quickstart-solace-vmr/
